# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for building the newsnet executable."""

import os
import sys

block_cipher = None

a = Analysis(
    ['cli/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('tui/app.tcss', 'tui'),
    ],
    hiddenimports=[
        # App modules
        'newsnet',
        'newsnet.config',
        'newsnet.node',
        'newsnet.store',
        'newsnet.filters',
        'newsnet.article',
        'newsnet.identity',
        'newsnet.sync',
        'cli',
        'tui',
        'tui.app',
        'umsgpack',
        'textual',
        # RNS core
        'RNS',
        'RNS.Channel',
        # RNS interfaces (dynamically loaded based on config)
        'RNS.Interfaces',
        'RNS.Interfaces.Interface',
        'RNS.Interfaces.LocalInterface',
        'RNS.Interfaces.AutoInterface',
        'RNS.Interfaces.BackboneInterface',
        'RNS.Interfaces.TCPInterface',
        'RNS.Interfaces.UDPInterface',
        'RNS.Interfaces.I2PInterface',
        'RNS.Interfaces.SerialInterface',
        'RNS.Interfaces.PipeInterface',
        'RNS.Interfaces.KISSInterface',
        'RNS.Interfaces.AX25KISSInterface',
        'RNS.Interfaces.RNodeInterface',
        'RNS.Interfaces.RNodeMultiInterface',
        'RNS.Interfaces.WeaveInterface',
        'RNS.Interfaces.Android',
        'RNS.Interfaces.Android.RNodeInterface',
        'RNS.Interfaces.Android.SerialInterface',
        'RNS.Interfaces.Android.KISSInterface',
        'RNS.Interfaces.util',
        'RNS.Interfaces.util.netinfo',
        # RNS cryptography (dynamic backend selection)
        'RNS.Cryptography',
        'RNS.Cryptography.Provider',
        'RNS.Cryptography.X25519',
        'RNS.Cryptography.Ed25519',
        'RNS.Cryptography.Proxies',
        'RNS.Cryptography.Hashes',
        'RNS.Cryptography.HKDF',
        'RNS.Cryptography.PKCS7',
        'RNS.Cryptography.Token',
        'RNS.Cryptography.AES',
        'RNS.Cryptography.SHA256',
        'RNS.Cryptography.SHA512',
        'RNS.Cryptography.HMAC',
        'RNS.Cryptography.aes',
        'RNS.Cryptography.aes.aes128',
        'RNS.Cryptography.aes.aes256',
        'RNS.Cryptography.pure25519',
        'RNS.Cryptography.pure25519.basic',
        'RNS.Cryptography.pure25519.ed25519_oop',
        'RNS.Cryptography.pure25519._ed25519',
        'RNS.Cryptography.pure25519.eddsa',
        # RNS vendors
        'RNS.vendor',
        'RNS.vendor.platformutils',
        'RNS.vendor.configobj',
        'RNS.vendor.umsgpack',
        'RNS.vendor.i2plib',
        'RNS.vendor.i2plib.sam',
        'RNS.vendor.i2plib.tunnel',
        'RNS.vendor.i2plib.aiosam',
        'RNS.vendor.i2plib.exceptions',
        'RNS.vendor.i2plib.log',
        'RNS.vendor.i2plib.utils',
    ],
    hookspath=['pyinstaller_hooks'],
    hooksconfig={},
    runtime_hooks=['pyinstaller_hooks/rthook_rns.py'],
    excludes=[],
    noarchive=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='newsnet',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
)
